export const UPDATE_NOTEBOOKS = 'UPDATE_NOTEBOOKS';
export const NOTEBOOK_CHANGE = 'NOTEBOOK_CHANGE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_SIDEBAR = 'SET_SIDEBAR';
export const SET_SIDEBAR_TYPE = 'SET_SIDEBAR_TYPE';
export const UPDATE_USER = 'UPDATE_USER';
